# Generated by Django 3.0.3 on 2021-02-25 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='company',
        ),
    ]
