# Generated by Django 3.0.3 on 2021-02-26 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20210226_0006'),
        ('accounts', '0002_remove_account_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Company'),
        ),
    ]
