# Generated by Django 3.0.3 on 2021-02-27 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_account_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='website_url',
        ),
    ]
