# Generated by Django 3.0.3 on 2021-02-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('company_logo', models.ImageField(default='C:\\Users\\x20195893\\Documents\\Freelance\\Freelancer\\block0x\\westfolks\\static\\static_rootassets/img/default.png', null=True, upload_to='user_profiles/images/')),
                ('company_mantra', models.TextField(blank=True, max_length=300, null=True)),
                ('company_description', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
