# Generated by Django 3.0.3 on 2021-02-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20210225_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(default='default/img/default.png', null=True, upload_to='default/img/'),
        ),
    ]
