# Generated by Django 3.0.3 on 2021-02-25 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20210225_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='account',
        ),
    ]
