# Generated by Django 3.0.3 on 2021-02-25 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_company'),
        ('company', '0008_remove_company_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
