# Generated by Django 3.0.3 on 2021-02-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20210225_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='account',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
