# Generated by Django 3.0.3 on 2021-02-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20210226_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
