# Generated by Django 3.0.3 on 2021-02-26 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_company_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_mantra',
            new_name='mantra',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='name',
        ),
    ]
