# Generated by Django 3.0.3 on 2021-02-26 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_auto_20210226_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='company_name',
        ),
    ]
