# Generated by Django 3.0.3 on 2021-02-26 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_account_company'),
        ('company', '0018_auto_20210226_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
    ]
