# Generated by Django 3.0.3 on 2021-02-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_auto_20210226_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
