# Generated by Django 3.0.3 on 2021-02-26 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_auto_20210226_1214'),
        ('products', '0002_auto_20210225_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='default', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('company', 'product_name')},
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
