# Generated by Django 3.0.3 on 2021-03-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210228_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
